<?php

namespace EI\AdminBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll()
    {

      $queryBuilder = $this->createQueryBuilder('c');

      // On récupère la Query à partir du QueryBuilder
      $query = $queryBuilder->getQuery();

      // On récupère les résultats à partir de la Query
      $results = $query->getResult();

      // On retourne ces résultats
      return $results;
    }
    
//    public function myFindOne($categoryId)
//    {
//      $qb = $this->createQueryBuilder('c');
//
//      $qb
//        ->where('c.id = :categoryId')
//        ->setParameter('categoryId', $categoryId)
//        ->leftJoin('c.brs', 'brs')
//              ->addSelect('brs')
//      ;
//
//      return $qb
//        ->getQuery()
//        ->getOneOrNullResult()
//      ;
//    }
    
     public function getCategoryWithImages(array $imageNames)
    {
      $qb = $this->createQueryBuilder('c');


      $qb
        ->join('c.images', 'i')
        ->addSelect('i')
      ;


      $qb->where($qb->expr()->in('i.name', $imageNames));



      return $qb
        ->getQuery()
        ->getResult()
      ;
    }
}
