<?php

namespace EI\AdminBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
     public function myFindAll()
    {

      $queryBuilder = $this->createQueryBuilder('e');

      // On récupère la Query à partir du QueryBuilder
      $query = $queryBuilder->getQuery();

      // On récupère les résultats à partir de la Query
      $results = $query->getResult();

      // On retourne ces résultats
      return $results;
    }
    
    public function getEventWithImages(array $imageNames)
    {
      $qb = $this->createQueryBuilder('e');


      $qb
        ->join('e.images', 'i')
        ->addSelect('i')
      ;


      $qb->where($qb->expr()->in('i.name', $imageNames));



      return $qb
        ->getQuery()
        ->getResult()
      ;
    }
}
