<?php

namespace EI\AdminBundle\Repository;

/**
 * HomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeRepository extends \Doctrine\ORM\EntityRepository
{
     public function myFindAll()
  {

    $queryBuilder = $this->createQueryBuilder('h');

    // On récupère la Query à partir du QueryBuilder
    $query = $queryBuilder->getQuery();

    // On récupère les résultats à partir de la Query
    $results = $query->getResult();

    // On retourne ces résultats
    return $results;
  }
}
