# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: bcrypt
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:    main
            form_login:
              login_path: fos_user_security_login
              check_path: fos_user_security_check
              default_target_path:     /viewUserPage
            logout:
              path:       fos_user_security_logout
              target:     /index
#            remember_me:
#              key:  %secret%
        
#        main_login:
#            # Cette expression régulière permet de prendre /login (mais pas /login_check !)
#            pattern:   ^/login$
#            anonymous: true # On autorise alors les anonymes sur ce pare-feu
#        main:
#            pattern:   ^/
#            anonymous: false
#            # activate different ways to authenticate
#
#            # http_basic: ~
#            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#
#            # form_login: ~
#            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
    access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/viewUserPage, role: [ROLE_USER, IS_AUTHENTICATED_FULLY] }
        - { path: ^/admin, role: [ROLE_ADMIN] }